# Generated by Django 2.1.7 on 2019-04-15 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_manufacturar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Doctor')),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturar',
            name='Address',
            field=models.CharField(max_length=50),
        ),
    ]
