# Generated by Django 2.1.7 on 2019-04-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190415_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
