# Generated by Django 2.1.7 on 2019-04-15 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190415_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('invoice_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grand_total', models.CharField(max_length=15)),
                ('amount_received', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Patient'),
        ),
    ]
