# Generated by Django 2.1.7 on 2019-04-17 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20190415_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('medicine_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=40)),
                ('cost', models.CharField(max_length=10)),
                ('medicine_type', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
