# Generated by Django 2.1.7 on 2019-04-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturar_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugs_type', models.CharField(max_length=30)),
                ('amount_paid', models.CharField(max_length=15)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Manufacturar')),
            ],
        ),
    ]
