# Generated by Django 2.1.7 on 2019-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_manufacturar_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20)),
                ('hire_date', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
